//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameFootball.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public int PlayerId { get; set; }
        public string Name { get; set; }
        public string BirthDate { get; set; }
        public string Description { get; set; }
        public string TeamId { get; set; }
        public int TeamTeamId { get; set; }
    
        public virtual Team Team { get; set; }
    }
}
